### ISSUE TITLE
Countdown Watch Widget Never Updates

### ISSUE THREAD

**Issue by ssnkhan** [daneden/Solstice#79] opened 2023-08-18 21:52 UTC
Hello,

The “Countdown” widget never appears to render, remaining as a placeholder consisting of a square and line. Latest versions of iOS 15, on Ultra. Thanks!

**Comment by daneden** [comment] 2024-06-26 12:15
Thanks for filing this bug @ssnkhan! I’ve found a fix that is planned for v2.2. Closing this issue as a duplicate of #90, where progress will be updated.

**Closed by daneden** 2024-06-26 12:15 UTC
